language: php

php:
  - 5.3
  - 5.4

before_script: composer install --dev --prefer-source --no-interaction

script: phpunit -c tests --coverage-text

notifications:
  email:
    - sysadmin@my-wardrobe.com